// Liste complète des activités professionnelles pour les formulaires d'enregistrement
export const ACTIVITES_PROFESSIONNELLES = [
  // Agriculture et élevage
  'Agriculteur/Agricultrice',
  'Éleveur/Éleveuse',
  'Pêcheur/Pêcheuse',
  'Forestier/Forestière',
  'Vétérinaire',
  
  // Artisanat et métiers manuels
  'Artisan/Artisane',
  'Mécanicien/Mécanicienne',
  'Mécanicien auto',
  'Mécanicien moto',
  'Garagiste',
  'Électricien/Électricienne',
  'Plombier/Plombière',
  'Menuisier/Menuisière',
  'Ébéniste',
  'Charpentier/Charpentière',
  'Maçon/Maçonne',
  'Peintre en bâtiment',
  'Carreleur/Carreleuse',
  'Serrurier/Serrurière',
  'Soudeur/Soudeuse',
  'Forgeron/Forgeronne',
  'Tailleur/Tailleuse',
  'Couturier/Couturière',
  'Styliste',
  'Modéliste',
  'Cordonnier/Cordonnière',
  'Bijoutier/Bijoutière',
  'Horloger/Horlogère',
  'Potier/Potière',
  'Tisserand/Tisserande',
  
  // Commerce et services
  'Commerçant/Commerçante',
  'Vendeur/Vendeuse',
  'Caissier/Caissière',
  'Chef d\'entreprise',
  'Entrepreneur/Entrepreneuse',
  'PDG (Président Directeur Général)',
  'Directeur commercial',
  'Agent immobilier',
  'Gestionnaire de patrimoine',
  'Transporteur/Transporteuse',
  'Chauffeur/Chauffeuse',
  'Chauffeur de taxi',
  'Conducteur de bus',
  'Guide touristique',
  'Hôtelier/Hôtelière',
  'Restaurateur/Restauratrice',
  'Cuisinier/Cuisinière',
  'Chef cuisinier',
  'Pâtissier/Pâtissière',
  'Boulanger/Boulangère',
  'Serveur/Serveuse',
  'Barman/Barmaid',
  'Coiffeur/Coiffeuse',
  'Esthéticien/Esthéticienne',
  'Barbier',
  'Agent d\'entretien',
  'Femme/Homme de ménage',
  'Blanchisseur/Blanchisseuse',
  
  // Éducation et formation
  'Écolier/Écolière',
  'Élève',
  'Collégien/Collégienne',
  'Lycéen/Lycéenne',
  'Étudiant/Étudiante',
  'Doctorant/Doctorante',
  'Enseignant/Enseignante',
  'Professeur',
  'Maître/Maîtresse d\'école',
  'Directeur/Directrice d\'école',
  'Proviseur',
  'Principal/Principale',
  'Recteur/Rectrice',
  'Chancelier',
  'Doyen/Doyenne',
  'Formateur/Formatrice',
  'Éducateur/Éducatrice',
  'Instituteur/Institutrice',
  
  // Santé et médical
  'Médecin',
  'Infirmier/Infirmière',
  'Pharmacien/Pharmacienne',
  'Dentiste',
  'Sage-femme',
  'Aide-soignant/Aide-soignante',
  'Kinésithérapeute',
  'Psychologue',
  'Psychiatre',
  'Technicien/Technicienne de laboratoire',
  
  // Ingénierie et technique
  'Ingénieur',
  'Architecte',
  'Technicien/Technicienne',
  'Informaticien/Informaticienne',
  'Développeur/Développeuse',
  'Designer',
  'Urbaniste',
  'Géographe',
  
  // Droit et justice
  'Avocat/Avocate',
  'Juge',
  'Magistrat/Magistrate',
  'Procureur',
  'Juge d\'instruction',
  'Président de tribunal',
  'Notaire',
  'Huissier/Huissière de justice',
  'Greffier/Greffière',
  'Juriste',
  'Conseiller juridique',
  'Avoué',
  
  // Sécurité et défense
  'Général',
  'Colonel',
  'Commandant',
  'Capitaine',
  'Lieutenant',
  'Sergent',
  'Soldat',
  'Militaire',
  'Officier',
  'Gendarme',
  'Policier/Policière',
  'Commissaire',
  'Inspecteur/Inspectrice',
  'Agent de police',
  'Agent de sécurité',
  'Garde du corps',
  'Détective privé',
  'Garde républicain',
  'Pompier/Pompière',
  'Ambulancier/Ambulancière',
  'Secouriste',
  'Agent de protection civile',
  
  // Transport et logistique
  'Pilote',
  'Hôtesse de l\'air/Steward',
  'Contrôleur aérien',
  'Marin',
  'Douanier/Douanière',
  'Agent de migration',
  
  // Politique et gouvernance
  'Président/Présidente de la République',
  'Premier Ministre',
  'Vice-Président/Vice-Présidente',
  'Ministre',
  'Secrétaire d\'État',
  'Député/Députée',
  'Sénateur/Sénatrice',
  'Parlementaire',
  'Maire',
  'Adjoint au Maire',
  'Conseiller municipal',
  'Conseiller régional',
  'Conseiller départemental',
  'Gouverneur',
  'Préfet',
  'Sous-préfet',
  'Chef de village',
  'Chef de canton',
  'Chef de province',
  'Diplomate',
  'Ambassadeur/Ambassadrice',
  'Consul',
  
  // Royauté et noblesse
  'Roi/Reine',
  'Prince/Princesse',
  'Duc/Duchesse',
  'Comte/Comtesse',
  'Baron/Baronne',
  'Sultan/Sultane',
  'Émir/Émirat',
  'Chef tribal',
  'Noble',
  
  // Administration et fonction publique
  'Fonctionnaire',
  'Secrétaire général',
  'Directeur général',
  'Directeur de cabinet',
  'Chef de service',
  'Secrétaire',
  'Assistant/Assistante',
  'Comptable',
  'Employé de bureau',
  'Agent administratif',
  'Gestionnaire',
  
  // Finance et banque
  'Banquier/Banquière',
  'Directeur/Directrice de banque',
  'Conseiller/Conseillère bancaire',
  'Agent de crédit',
  'Analyste financier',
  'Trader',
  'Courtier/Courtière',
  'Auditeur/Auditrice',
  'Contrôleur/Contrôleuse de gestion',
  'Expert-comptable',
  'Fiscaliste',
  'Trésorier/Trésorière',
  'Agent de change',
  
  // Médias et communication
  'Journaliste',
  'Rédacteur/Rédactrice en chef',
  'Reporter',
  'Présentateur/Présentatrice TV',
  'Animateur/Animatrice radio',
  'Chroniqueur/Chroniqueuse',
  'Photographe',
  'Cameraman/Camerawoman',
  'Réalisateur/Réalisatrice',
  'Producteur/Productrice',
  'Monteur/Monteuse',
  'Scénariste',
  'Traducteur/Traductrice',
  'Interprète',
  'Chargé/Chargée de communication',
  'Attaché/Attachée de presse',
  'Community manager',
  'Influenceur/Influenceuse',
  'Blogueur/Blogueuse',
  'Youtubeur/Youtubeuse',
  
  // Arts et culture
  'Artiste',
  'Musicien/Musicienne',
  'Chanteur/Chanteuse',
  'Rappeur/Rappeuse',
  'DJ (Disc Jockey)',
  'Compositeur/Compositrice',
  'Chef d\'orchestre',
  'Danseur/Danseuse',
  'Chorégraphe',
  'Acteur/Actrice',
  'Comédien/Comédienne',
  'Humoriste',
  'Écrivain/Écrivaine',
  'Auteur/Auteure',
  'Romancier/Romancière',
  'Poète/Poétesse',
  'Conteur/Conteuse',
  'Sculpteur/Sculptrice',
  'Peintre artiste',
  'Dessinateur/Dessinatrice',
  'Graphiste',
  'Illustrateur/Illustratrice',
  'Conservateur/Conservatrice de musée',
  'Critique d\'art',
  
  // Religion et spiritualité
  'Imam',
  'Prêtre',
  'Pasteur',
  'Évêque',
  'Cardinal',
  'Archevêque',
  'Pape',
  'Moine/Moniale',
  'Religieux/Religieuse',
  'Missionnaire',
  'Prédicateur/Prédicatrice',
  'Catéchiste',
  'Diacre',
  'Rabbin',
  'Grand Imam',
  'Mufti',
  'Cheikh',
  'Marabout',
  'Chef religieux',
  'Théologien/Théologienne',
  'Exégète',
  
  // Recherche et sciences
  'Chercheur/Chercheuse',
  'Scientifique',
  'Historien/Historienne',
  'Sociologue',
  'Anthropologue',
  'Archéologue',
  
  // Sports et loisirs
  'Sportif/Sportive professionnel(le)',
  'Footballeur/Footballeuse',
  'Basketteur/Basketteuse',
  'Athlète',
  'Entraîneur/Entraîneuse',
  'Coach sportif',
  'Arbitre',
  'Commentateur/Commentatrice sportif',
  
  // ONG et humanitaire
  'Travailleur/Travailleuse humanitaire',
  'Bénévole',
  'Coordinateur/Coordinatrice ONG',
  'Chargé/Chargée de projet',
  'Volontaire',
  
  // Consulting et conseil
  'Consultant/Consultante',
  'Conseiller/Conseillère',
  'Expert/Experte',
  'Analyste',
  'Stratège',
  
  // Autres
  'Retraité/Retraitée',
  'Pensionné/Pensionnée',
  'Chômeur/Chômeuse',
  'Sans emploi',
  'En recherche d\'emploi',
  'Au foyer',
  'Femme/Homme au foyer',
  'Bébé',
  'Enfant',
  'Mineur',
  'Autre'
]

// Catégories d'activités pour faciliter la navigation
export const CATEGORIES_ACTIVITES = {
  'Agriculture et élevage': [
    'Agriculteur/Agricultrice',
    'Éleveur/Éleveuse',
    'Pêcheur/Pêcheuse',
    'Forestier/Forestière',
    'Vétérinaire'
  ],
  
  'Artisanat et métiers manuels': [
    'Artisan/Artisane',
    'Mécanicien/Mécanicienne',
    'Mécanicien auto',
    'Mécanicien moto',
    'Garagiste',
    'Électricien/Électricienne',
    'Plombier/Plombière',
    'Menuisier/Menuisière',
    'Ébéniste',
    'Charpentier/Charpentière',
    'Maçon/Maçonne',
    'Peintre en bâtiment',
    'Carreleur/Carreleuse',
    'Serrurier/Serrurière',
    'Soudeur/Soudeuse',
    'Forgeron/Forgeronne',
    'Tailleur/Tailleuse',
    'Couturier/Couturière',
    'Styliste',
    'Modéliste',
    'Cordonnier/Cordonnière',
    'Bijoutier/Bijoutière',
    'Horloger/Horlogère',
    'Potier/Potière',
    'Tisserand/Tisserande'
  ],
  
  'Commerce et services': [
    'Commerçant/Commerçante',
    'Vendeur/Vendeuse',
    'Caissier/Caissière',
    'Chef d\'entreprise',
    'Entrepreneur/Entrepreneuse',
    'PDG (Président Directeur Général)',
    'Directeur commercial',
    'Agent immobilier',
    'Gestionnaire de patrimoine',
    'Transporteur/Transporteuse',
    'Chauffeur/Chauffeuse',
    'Chauffeur de taxi',
    'Conducteur de bus',
    'Guide touristique',
    'Hôtelier/Hôtelière',
    'Restaurateur/Restauratrice',
    'Cuisinier/Cuisinière',
    'Chef cuisinier',
    'Pâtissier/Pâtissière',
    'Boulanger/Boulangère',
    'Serveur/Serveuse',
    'Barman/Barmaid',
    'Coiffeur/Coiffeuse',
    'Esthéticien/Esthéticienne',
    'Barbier',
    'Agent d\'entretien',
    'Femme/Homme de ménage',
    'Blanchisseur/Blanchisseuse'
  ],
  
  'Éducation et formation': [
    'Écolier/Écolière',
    'Élève',
    'Collégien/Collégienne',
    'Lycéen/Lycéenne',
    'Étudiant/Étudiante',
    'Doctorant/Doctorante',
    'Enseignant/Enseignante',
    'Professeur',
    'Maître/Maîtresse d\'école',
    'Directeur/Directrice d\'école',
    'Proviseur',
    'Principal/Principale',
    'Recteur/Rectrice',
    'Chancelier',
    'Doyen/Doyenne',
    'Formateur/Formatrice',
    'Éducateur/Éducatrice',
    'Instituteur/Institutrice'
  ],
  
  'Santé et médical': [
    'Médecin',
    'Infirmier/Infirmière',
    'Pharmacien/Pharmacienne',
    'Dentiste',
    'Sage-femme',
    'Aide-soignant/Aide-soignante',
    'Kinésithérapeute',
    'Psychologue',
    'Psychiatre',
    'Technicien/Technicienne de laboratoire'
  ],
  
  'Ingénierie et technique': [
    'Ingénieur',
    'Architecte',
    'Technicien/Technicienne',
    'Informaticien/Informaticienne',
    'Développeur/Développeuse',
    'Designer',
    'Urbaniste',
    'Géographe'
  ],
  
  'Droit et justice': [
    'Avocat/Avocate',
    'Juge',
    'Magistrat/Magistrate',
    'Procureur',
    'Juge d\'instruction',
    'Président de tribunal',
    'Notaire',
    'Huissier/Huissière de justice',
    'Greffier/Greffière',
    'Juriste',
    'Conseiller juridique',
    'Avoué'
  ],
  
  'Sécurité et défense': [
    'Général',
    'Colonel',
    'Commandant',
    'Capitaine',
    'Lieutenant',
    'Sergent',
    'Soldat',
    'Militaire',
    'Officier',
    'Gendarme',
    'Policier/Policière',
    'Commissaire',
    'Inspecteur/Inspectrice',
    'Agent de police',
    'Agent de sécurité',
    'Garde du corps',
    'Détective privé',
    'Garde républicain',
    'Pompier/Pompière',
    'Ambulancier/Ambulancière',
    'Secouriste',
    'Agent de protection civile'
  ],
  
  'Transport et logistique': [
    'Pilote',
    'Hôtesse de l\'air/Steward',
    'Contrôleur aérien',
    'Marin',
    'Douanier/Douanière',
    'Agent de migration'
  ],
  
  'Politique et gouvernance': [
    'Président/Présidente de la République',
    'Premier Ministre',
    'Vice-Président/Vice-Présidente',
    'Ministre',
    'Secrétaire d\'État',
    'Député/Députée',
    'Sénateur/Sénatrice',
    'Parlementaire',
    'Maire',
    'Adjoint au Maire',
    'Conseiller municipal',
    'Conseiller régional',
    'Conseiller départemental',
    'Gouverneur',
    'Préfet',
    'Sous-préfet',
    'Chef de village',
    'Chef de canton',
    'Chef de province',
    'Diplomate',
    'Ambassadeur/Ambassadrice',
    'Consul'
  ],
  
  'Royauté et noblesse': [
    'Roi/Reine',
    'Prince/Princesse',
    'Duc/Duchesse',
    'Comte/Comtesse',
    'Baron/Baronne',
    'Sultan/Sultane',
    'Émir/Émirat',
    'Chef tribal',
    'Noble'
  ],
  
  'Administration et fonction publique': [
    'Fonctionnaire',
    'Secrétaire général',
    'Directeur général',
    'Directeur de cabinet',
    'Chef de service',
    'Secrétaire',
    'Assistant/Assistante',
    'Comptable',
    'Employé de bureau',
    'Agent administratif',
    'Gestionnaire'
  ],
  
  'Finance et banque': [
    'Banquier/Banquière',
    'Directeur/Directrice de banque',
    'Conseiller/Conseillère bancaire',
    'Agent de crédit',
    'Analyste financier',
    'Trader',
    'Courtier/Courtière',
    'Auditeur/Auditrice',
    'Contrôleur/Contrôleuse de gestion',
    'Expert-comptable',
    'Fiscaliste',
    'Trésorier/Trésorière',
    'Agent de change'
  ],
  
  'Médias et communication': [
    'Journaliste',
    'Rédacteur/Rédactrice en chef',
    'Reporter',
    'Présentateur/Présentatrice TV',
    'Animateur/Animatrice radio',
    'Chroniqueur/Chroniqueuse',
    'Photographe',
    'Cameraman/Camerawoman',
    'Réalisateur/Réalisatrice',
    'Producteur/Productrice',
    'Monteur/Monteuse',
    'Scénariste',
    'Traducteur/Traductrice',
    'Interprète',
    'Chargé/Chargée de communication',
    'Attaché/Attachée de presse',
    'Community manager',
    'Influenceur/Influenceuse',
    'Blogueur/Blogueuse',
    'Youtubeur/Youtubeuse'
  ],
  
  'Arts et culture': [
    'Artiste',
    'Musicien/Musicienne',
    'Chanteur/Chanteuse',
    'Rappeur/Rappeuse',
    'DJ (Disc Jockey)',
    'Compositeur/Compositrice',
    'Chef d\'orchestre',
    'Danseur/Danseuse',
    'Chorégraphe',
    'Acteur/Actrice',
    'Comédien/Comédienne',
    'Humoriste',
    'Écrivain/Écrivaine',
    'Auteur/Auteure',
    'Romancier/Romancière',
    'Poète/Poétesse',
    'Conteur/Conteuse',
    'Sculpteur/Sculptrice',
    'Peintre artiste',
    'Dessinateur/Dessinatrice',
    'Graphiste',
    'Illustrateur/Illustratrice',
    'Conservateur/Conservatrice de musée',
    'Critique d\'art'
  ],
  
  'Religion et spiritualité': [
    'Imam',
    'Prêtre',
    'Pasteur',
    'Évêque',
    'Cardinal',
    'Archevêque',
    'Pape',
    'Moine/Moniale',
    'Religieux/Religieuse',
    'Missionnaire',
    'Prédicateur/Prédicatrice',
    'Catéchiste',
    'Diacre',
    'Rabbin',
    'Grand Imam',
    'Mufti',
    'Cheikh',
    'Marabout',
    'Chef religieux',
    'Théologien/Théologienne',
    'Exégète'
  ],
  
  'Recherche et sciences': [
    'Chercheur/Chercheuse',
    'Scientifique',
    'Historien/Historienne',
    'Sociologue',
    'Anthropologue',
    'Archéologue'
  ],
  
  'Sports et loisirs': [
    'Sportif/Sportive professionnel(le)',
    'Footballeur/Footballeuse',
    'Basketteur/Basketteuse',
    'Athlète',
    'Entraîneur/Entraîneuse',
    'Coach sportif',
    'Arbitre',
    'Commentateur/Commentatrice sportif'
  ],
  
  'ONG et humanitaire': [
    'Travailleur/Travailleuse humanitaire',
    'Bénévole',
    'Coordinateur/Coordinatrice ONG',
    'Chargé/Chargée de projet',
    'Volontaire'
  ],
  
  'Consulting et conseil': [
    'Consultant/Consultante',
    'Conseiller/Conseillère',
    'Expert/Experte',
    'Analyste',
    'Stratège'
  ],
  
  'Autres': [
    'Retraité/Retraitée',
    'Pensionné/Pensionnée',
    'Chômeur/Chômeuse',
    'Sans emploi',
    'En recherche d\'emploi',
    'Au foyer',
    'Femme/Homme au foyer',
    'Bébé',
    'Enfant',
    'Mineur',
    'Autre'
  ]
}











